# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildOutput: 'build'
  package.id: 'rest-api-calculator'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -DskipTests'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      [xml]$pomXml = Get-Content .\pom.xml
        # version
        Write-Host $pomXml.project.version
        $version=$pomXml.project.version
        Write-Host "##vso[task.setvariable variable=version]$version"
  displayName: 'Get versio from pom'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(buildOutput)'
  displayName: 'copying jar files to build output folder'

- task: OctopusPack@4
  inputs:
    PackageId: '$(package.id)'
    PackageFormat: 'Zip'
    PackageVersion: '$(version)'
    SourcePath: '$(buildOutput)/target'
    OutputPath: '$(Build.ArtifactStagingDirectory)/packages'

- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'octopus deploy'
    Space: 'Spaces-2'
    Package: '$(Build.ArtifactStagingDirectory)/packages/*.zip'
    Replace: 'true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'